import type { ExecutiveReport, MigrationConstraints, MigrationRoadmap, RiskScenarioResult, ScanComparison, ScanHistoryItem, ScanSummary } from "./types";

export const API_BASE = process.env.NEXT_PUBLIC_ECDAT_API_BASE_URL ?? "http://localhost:8000";
async function fail(response: Response, label: string): Promise<never> { const message = await response.text(); throw new Error(`${label} (${response.status}): ${message}`); }

export type ReferenceAssessmentOptions = {
  display_name?: string; environment?: string; owner?: string; team?: string;
  data_lifetime_years?: number; migration_time_years?: number; data_sensitivity?: string; business_criticality?: string;
  public_exposure?: boolean; confidentiality_required?: boolean;
};

export async function runReferenceAssessment(quantumHorizonYears = 15, options: ReferenceAssessmentOptions = {}): Promise<ScanSummary> {
  const query = new URLSearchParams({ quantum_horizon_years: String(quantumHorizonYears) });
  for (const [key, value] of Object.entries(options)) if (value !== undefined) query.set(key, String(value));
  const response = await fetch(`${API_BASE}/v1/scans/reference?${query}`, { method: "POST" });
  if (!response.ok) return fail(response, "Reference assessment failed");
  return response.json() as Promise<ScanSummary>;
}

export async function scanMountedPath(payload: { path: string; display_name: string; environment: string; owner: string; team: string; quantum_horizon_years: number; data_lifetime_years: number; migration_time_years: number; data_sensitivity: string; business_criticality: string; public_exposure: boolean; confidentiality_required: boolean }): Promise<ScanSummary> {
  const response = await fetch(`${API_BASE}/v1/scans/directory`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ path: payload.path, display_name: payload.display_name, environment: payload.environment, owner: payload.owner, team: payload.team, source_name: "Mounted workspace", risk_context: { data_lifetime_years: payload.data_lifetime_years, migration_time_years: payload.migration_time_years, quantum_horizon_years: payload.quantum_horizon_years, data_sensitivity: payload.data_sensitivity, business_criticality: payload.business_criticality, public_exposure: payload.public_exposure, confidentiality_required: payload.confidentiality_required } }) });
  if (!response.ok) return fail(response, "Directory assessment failed"); return response.json() as Promise<ScanSummary>;
}
export async function uploadEnterpriseArchive(file: File, options: Record<string, string | number | boolean>): Promise<ScanSummary> { const form = new FormData(); form.append("file", file); Object.entries(options).forEach(([key, value]) => form.append(key, String(value))); const response = await fetch(`${API_BASE}/v1/intake/archive`, { method: "POST", body: form }); if (!response.ok) return fail(response, "Archive intake failed"); return response.json() as Promise<ScanSummary>; }
export async function uploadContainerArchive(file: File, options: Record<string, string | number | boolean>): Promise<ScanSummary> { const form = new FormData(); form.append("file", file); Object.entries(options).forEach(([key, value]) => form.append(key, String(value))); const response = await fetch(`${API_BASE}/v1/intake/container`, { method: "POST", body: form }); if (!response.ok) return fail(response, "Container image intake failed"); return response.json() as Promise<ScanSummary>; }
export async function uploadCycloneDx(file: File, options: Record<string, string | number | boolean>): Promise<ScanSummary> { const form = new FormData(); form.append("file", file); Object.entries(options).forEach(([key, value]) => form.append(key, String(value))); const response = await fetch(`${API_BASE}/v1/intake/bom`, { method: "POST", body: form }); if (!response.ok) return fail(response, "CBOM intake failed"); return response.json() as Promise<ScanSummary>; }
export async function fetchLatestScan(): Promise<ScanSummary | null> { const response = await fetch(`${API_BASE}/v1/scans/latest`, { cache: "no-store" }); if (response.status === 404) return null; if (!response.ok) return fail(response, "Unable to load latest assessment"); return response.json() as Promise<ScanSummary>; }
export async function fetchScan(scanId: string): Promise<ScanSummary> { const response = await fetch(`${API_BASE}/v1/scans/${scanId}`, { cache: "no-store" }); if (!response.ok) return fail(response, "Unable to load assessment"); return response.json() as Promise<ScanSummary>; }
export async function fetchScanHistory(limit = 30): Promise<ScanHistoryItem[]> { const response = await fetch(`${API_BASE}/v1/scans?limit=${limit}`, { cache: "no-store" }); if (!response.ok) return fail(response, "Unable to load assessment history"); return response.json() as Promise<ScanHistoryItem[]>; }
export async function compareScans(baseId: string, targetId: string): Promise<ScanComparison> { const query = new URLSearchParams({ base_id: baseId, target_id: targetId }); const response = await fetch(`${API_BASE}/v1/scans/compare?${query}`, { cache: "no-store" }); if (!response.ok) return fail(response, "Unable to compare assessments"); return response.json() as Promise<ScanComparison>; }
export async function evaluateRiskScenario(scanId: string, horizon: number): Promise<RiskScenarioResult> { const response = await fetch(`${API_BASE}/v1/risk/scenarios`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ scan_id: scanId, quantum_horizon_years: horizon }) }); if (!response.ok) return fail(response, "Scenario analysis failed"); return response.json() as Promise<RiskScenarioResult>; }
export async function buildMigrationPlan(constraints: MigrationConstraints, scanId?: string, quantumHorizonYears?: number): Promise<MigrationRoadmap> { const response = await fetch(`${API_BASE}/v1/migration/plans`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ scan_id: scanId ?? null, quantum_horizon_years: quantumHorizonYears ?? null, constraints }) }); if (!response.ok) return fail(response, "Migration plan failed"); return response.json() as Promise<MigrationRoadmap>; }
export async function fetchLatestMigrationPlan(): Promise<MigrationRoadmap | null> { const response = await fetch(`${API_BASE}/v1/migration/plans/latest`, { cache: "no-store" }); if (response.status === 404) return null; if (!response.ok) return fail(response, "Unable to load latest migration plan"); return response.json() as Promise<MigrationRoadmap>; }
export async function fetchExecutiveReport(scanId: string): Promise<ExecutiveReport> { const response = await fetch(`${API_BASE}/v1/reports/scans/${scanId}/executive`, { cache: "no-store" }); if (!response.ok) return fail(response, "Unable to generate executive report"); return response.json() as Promise<ExecutiveReport>; }
