server {
    listen 443 ssl;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256;
    ssl_certificate /etc/ecdat/certs/edge-rsa.crt;
    ssl_certificate_key /etc/ecdat/certs/edge-rsa.key;
}
